import { Badge } from '@/lib/types';

export const BADGES: Record<string, Badge> = {
  NEW_BEE: {
    id: 'new-bee',
    name: 'The New-Bee',
    description: 'First check-in as a member',
    icon: '🐝',
    color: 'honey',
    isMemberOnly: true,
  },
  EARLY_RISER: {
    id: 'early-riser',
    name: 'The Early Riser',
    description: 'Checked in before 8:00 AM five days in a row',
    icon: '🌅',
    color: 'ocean',
    isRepeatable: true,
  },
  MOONLIGHTER: {
    id: 'moonlighter',
    name: 'The Moonlighter',
    description: 'Still working after 7:00 PM',
    icon: '🌙',
    color: 'teal',
  },
  ANCHOR: {
    id: 'anchor',
    name: 'The Anchor',
    description: 'Used the same conference room 10+ times',
    icon: '⚓',
    color: 'teal',
    isRepeatable: true,
  },
  FULL_HOUSE: {
    id: 'full-house',
    name: 'The Full House',
    description: 'Checked in every single business day of a calendar month',
    icon: '🏠',
    color: 'honey',
    isRepeatable: true,
  },
  BUSY_BEE: {
    id: 'busy-bee',
    name: 'The Busy Bee',
    description: 'Attended three community-led events',
    icon: '🐝',
    color: 'honey',
  },
  CONNECTOR: {
    id: 'connector',
    name: 'The Connector',
    description: 'Successfully referred a new member or a guest',
    icon: '🤝',
    color: 'ocean',
    upsell: {
      title: 'Refer & Earn',
      description: 'Get $500 for every referral.',
      cta: 'Refer Now',
    },
  },
  POLLINATOR: {
    id: 'pollinator',
    name: 'The Pollinator',
    description: 'Visited 3+ Industrious locations within a city',
    icon: '🦋',
    color: 'sunset',
    isMemberOnly: true,
    upsell: {
      title: 'Access All Content',
      description: 'Upgrade to Access membership to visit any location.',
      cta: 'Upgrade',
    },
  },
  WORLD_TRAVELER: {
    id: 'world-traveler',
    name: 'The World Traveler',
    description: 'Visited 5+ locations in different cities',
    icon: '🌍',
    color: 'teal',
    isMemberOnly: true,
    upsell: {
      title: 'Go National',
      description: 'Travel freely with our National Access pass.',
      cta: 'Upgrade',
    },
  },
  STORM_RIDER: {
    id: 'storm-rider',
    name: 'The Storm Rider',
    description: 'Braved the elements during a snowstorm',
    icon: '❄️',
    color: 'grey',
  },
};
